bind 127.0.0.1
port 6380

protected-mode yes

# As this db is just used for task mashalling for tasks that are
# always rerun anyway, there is no need for durability here.
save ""
appendonly no

# Memory cap.
maxmemory 16gb
maxmemory-policy allkeys-lru