bind 127.0.0.1 192.168.1.98
port 6380

protected-mode yes

dir /home/dsicilia/.local/state/redist

# For an MVP cache/coordination server, you may not even need persistence:
save ""
appendonly no

# Optional memory cap later:
# maxmemory 8gb
# maxmemory-policy allkeys-lru