bind 127.0.0.1 192.168.1.98
port 6379

protected-mode yes

dir /home/dsicilia/.local/state/redis

# For an MVP cache/coordination server, you may not even need persistence:
save ""
appendonly no

# Allow basically all keyspace/keyevent pub/sub activity. This
# allows us to subscribe to changes related to keys.
notify-keyspace-events KEA

# Memory cap.
maxmemory 20gb
maxmemory-policy allkeys-lru